name: Add changeset to Renovate updates

on:
    merge_group:
    pull_request_target:
        paths:
            - '.github/workflows/changesets-renovate.yml'
            - '**/pnpm-lock.yaml'
            - '**/package.json'

jobs:
    generate-changesets:
        name: Generate changesets
        runs-on: ubuntu-latest
        timeout-minutes: 5
        if: github.actor == 'renovate[bot]'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.PAT_TOKEN }}

            - name: Git Identity
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            - name: Setup PNPM
              uses: pnpm/action-setup@v4

            - name: Run changesets-renovate
              run: pnpm dlx @scaleway/changesets-renovate
