name: Add changeset to Renovate updates

on:
    pull_request_target:
        types: [opened, synchronize, labeled]

jobs:
    generate-changesets:
        name: Generate changesets
        runs-on: ubuntu-latest
        timeout-minutes: 5
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        steps:
            - name: Update Pull Request
              uses: mscharley/dependency-changesets-action@v1.0.10
              with:
                  token: ${{ secrets.DEPENDENCY_UPDATE_GITHUB_TOKEN }}
                  use-conventional-commits: false
                  author-name: github-actions[bot]
                  author-email: 41898282+github-actions[bot]@users.noreply.github.com
