name: Add changeset to Renovate updates

on:
    merge_group:
    pull_request_target:
        paths:
            - '.github/workflows/changesets-renovate.yml'
            - '**/pnpm-lock.yaml'
            - '**/package.json'

jobs:
    generate-changesets:
        name: Generate changesets
        runs-on: ubuntu-latest
        timeout-minutes: 5
        if: github.actor == 'renovate[bot]'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.BOT_PAT_TOKEN }}
                  persist-credentials: false
                  fetch-depth: 2
                  ref: ${{ github.head_ref }}

            - name: Setup Git user
              run: |
                  git config --global user.name 'Julien Papini [bot]'
                  git config --global user.email 'julien.papini+github-bot@gmail.com'

                  git config --global commit.gpgSign true
                  git config --global tag.gpgSign true
                  git config --global gpg.format ssh
                  git config --global user.signingkey 'key::${{ secrets.BOT_SSH_PUBLIC_KEY }}'

                  eval `ssh-agent -s`
                  echo '${{ secrets.BOT_SSH_PRIVATE_KEY }}' | tr -d '\r' | ssh-add -

            - name: Setup PNPM
              uses: pnpm/action-setup@v4

            - name: Run changesets-renovate
              run: pnpm dlx @scaleway/changesets-renovate
