name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.BOT_PAT_TOKEN }}
                  persist-credentials: false

            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

            - name: Setup Git user
              run: |
                  git config --global user.name 'Julien Papini [bot]'
                  git config --global user.email 'julien.papini+github-bot@gmail.com'
                  git config --global commit.gpgSign true
                  git config --global tag.gpgSign true
                  git config --global gpg.format ssh
                  git config --global user.signingkey key::${{ secrets.BOT_SSH_PUBLIC_KEY }}

            - name: Setup PNPM
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  registry-url: 'https://registry.npmjs.org/'
                  node-version-file: package.json
                  cache: pnpm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Create release Pull Request
              id: changesets
              uses: changesets/action@v1
              with:
                  setupGitUser: false
                  title: 'Release package(s)'
                  commit: 'chore(version): bump package(s) version'
                  publish: pnpm changeset:publish
              env:
                  GITHUB_TOKEN: ${{ secrets.BOT_PAT_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
