name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.PAT_TOKEN }}

            - name: Setup PNPM
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  registry-url: 'https://registry.npmjs.org/'
                  node-version-file: package.json
                  cache: pnpm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Create release Pull Request
              id: changesets
              uses: changesets/action@v1
              with:
                  title: 'Release package(s)'
                  commit: 'chore(version): bump package(s) version'
                  publish: pnpm changeset:publish
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
